# Generated by Django 5.0.4 on 2024-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(default=None, max_length=255)),
                ('name', models.CharField(default=None, max_length=255)),
                ('parent', models.CharField(default=None, max_length=255)),
                ('flag_pc', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ration',
            fields=[
                ('id_ration', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('date', models.DateField()),
                ('count_pp', models.IntegerField()),
                ('count_day', models.IntegerField()),
                ('technologist', models.CharField(max_length=100)),
                ('done', models.IntegerField(default=0)),
                ('archive', models.IntegerField(default=0)),
            ],
        ),
    ]
