# Generated by Django 5.1.3 on 2024-11-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='composition',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ing_pc',
            fields=[
                ('code_ing', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('code_pc', models.CharField(max_length=12)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ing_pp',
            fields=[
                ('id_1', models.IntegerField(primary_key=True, serialize=False)),
                ('id_pp', models.IntegerField()),
                ('code', models.CharField(max_length=12)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('water', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('nlc', models.FloatField()),
                ('chol', models.FloatField()),
                ('mds', models.FloatField()),
                ('kr', models.FloatField()),
                ('carb', models.FloatField()),
                ('pv', models.FloatField()),
                ('ok', models.FloatField()),
                ('ash', models.FloatField()),
                ('na', models.FloatField()),
                ('k', models.FloatField()),
                ('ca', models.FloatField()),
                ('mg', models.FloatField()),
                ('p', models.FloatField()),
                ('fe', models.FloatField()),
                ('a', models.FloatField()),
                ('kar', models.FloatField()),
                ('re', models.FloatField()),
                ('te', models.FloatField()),
                ('b1', models.FloatField()),
                ('b2', models.FloatField()),
                ('pp', models.FloatField()),
                ('ne', models.FloatField()),
                ('c', models.FloatField()),
                ('ec', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='limit',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('id_ration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pc',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id_people', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pp',
            fields=[
                ('id_pp', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ration', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
