# Generated by Django 5.1.3 on 2024-11-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rationapp', '0002_composition_ing_pc_ing_pp_ingredients_limit_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ingredients', serialize=False, to='rationapp.general'),
        ),
    ]
