# Generated by Django 5.1.3 on 2024-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rationapp', '0004_rename_code_ingredients_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='flag_pc',
        ),
        migrations.AddField(
            model_name='pc',
            name='name',
            field=models.CharField(default='1', max_length=60, unique=True),
        ),
    ]
